name: cloudrun-deploy 

on: 
  push: 
    branches: 
      - main     
env:
    PROJECT_ID: us-gcp-ame-con-116-npd-1
    SERVICE_NAME: kisaan-backend
    REGION: us-west2

jobs: 
  build: 
    name: Cloud Run Deploy 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout 
        uses: actions/checkout@master 

      # Setup gcloud CLI 
      - uses: google-github-actions/setup-gcloud@v0 
        with: 
          service_account_key: ${{ secrets.GCP_SA_KEY}}            

      - name: Configure project id 
        run: | 
          gcloud config set project $PROJECT_ID

      #Build and Push image 
      - name: Build 
        run: |
          docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME ./Mutual-fund-app

      # Configure docker to use the gcloud command-line tool as a credential helper 
      - run: | 
          gcloud auth configure-docker -q 

      # Push image to Google Container Registry 
      - name: Push 
        run: |
          docker push gcr.io/$PROJECT_ID/$SERVICE_NAME

      - name: Deploy 
        run: |     
          gcloud run deploy $SERVICE_NAME --image gcr.io/$PROJECT_ID/$SERVICE_NAME --max-instances 3 --memory 1000Mi --platform managed --region $REGION --allow-unauthenticated # --vpc-connector hu-conn --add-cloudsql-instances huex-mysql 
